VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CChartSubTotal"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public SALE_ID As String
Public AREA_ID  As Long
Public GOODS_GROUP_ID As Long

      Public CUS_ID  As String
      Public TOTAL1_AMOUNT As Double
      Public TOTAL2_AMOUNT As Double
      Public MINUS As String
