VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CSubGroupTotal"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Public SUB_GROUP_TYPE_NAME As String
Public SUB_GROUP_TYPE_CODE As String
Public Column1  As Double
Public Column2  As Double
Public Column3  As Double
Public Column4  As Double
Public Column5  As Double
Public Column6  As Double
Public Column7  As Double
Public Column8  As Double
Public Column9  As Double
Public Column10  As Double
Public Column11  As Double
Public Column12  As Double
